name: Fly Deploy
on:
  push:
    paths:
      - 'socks/**'
    branches:
      - highscore
  pull_request:
    types: [opened, synchronize, reopened, closed]
    paths:
      - 'socks/**'
    branches:
      - highscore
env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: cd socks && flyctl deploy --remote-only
